#pragma once

enum component_t
{
    COMPONENT_BUTTON,
    COMPONENT_TEXT,
    COMPONENT_CHECKBOX,
    COMPONENT_TEXTBOX,
    COMPONENT_CONTAINER,
    COMPONENT_SCROLLBAR,
    COMPONENT_SCROLL_LIST,
    COMPONENT_BOX
};
